### ISSUE TITLE
Calender locale setting per instannce

### ISSUE THREAD

**Issue by Vishwaas** [cibernox/ember-power-datepicker#15]
@cibernox 
It doesn't appear as though the setting locale per instance basic for calender is implemented in ember-power-datepicker. Is this part of future release?

[Reference](http://www.ember-power-calendar.com/docs/i18n)
in particular the below implementation
```
{{#power-calendar locale="ru" as |calendar|}}
```

I tried doing below just to test the locale feature of calender in datepicker but that didn work too

```
{{#power-datepicker
  renderInPlace=true
  selected=selected
  onSelect=(action (mut selected) value="date")
  as |dp|
}}
  {{#dp.trigger tabindex="-1"}}
    <input type="text" class="form-control" readonly value={{selected}}>
  {{/dp.trigger}}

  {{assign-content dp localeSelected}} // this 0r below
  {{#dp.content class="dropdown-menu demo-datepicker-small"}}
  {{assign-content dp localeSelected}}
    {{dp.nav}}
    {{dp.days}}
  {{/dp.content}}
{{/power-datepicker}}
```
I was hoping something like
```
{{#power-datepicker
locale=instanceLocalevalue
...
```

thanks

**Comment by cibernox** [comment]
I am not forwarding that property to the inner calendar in the template, but it would be trivial to do so. If you can make a PR I can approve it and release it today.

**Comment by Vishwaas** [comment]
@cibernox yep I already saw that, true its trivial hence wanted to check. Sure will provide a PR by eod today.

**Comment by Vishwaas** [comment]
@cibernox I have made the changes but not able to push branch to create PR. Anything to be done?

**Comment by cibernox** [comment]
@Vishwaas Only the owner and collaborators of a repo have write permission on it. The usual flow is to **fork** this repo in your username, do the changes on your fork and then make a pull request from your fork to this one.

**Comment by Vishwaas** [comment]
@cibernox  Oops, PR provided : )

**Comment by Vishwaas** [comment]
Enhancement pushed [here](https://github.com/cibernox/ember-power-datepicker/pull/16)
Should be available in next release
