### ISSUE TITLE
problem against ember-cli-bootstrap-sassy?

### ISSUE THREAD

**Issue by greyhwndz** [cibernox/ember-power-datepicker#21]
created a new ember app (v2.15), installed `ember-cli-sass` & `ember-power-datepicker`: datepicker from the example in the readme was working.
installed `ember-cli-bootstrap-sassy`, suddenly the datepicker stopped working.
Could this be a problem with the default style in ember-power-datepicker?

**Comment by cibernox** [comment]
Updated the snippet in the readme to avoid class name clashing with bootstrap
