### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by markusm7** [cibernox/ember-power-datepicker#35]
This addon is using relatively old versions of your `ember-power-calendar` (0.9.2).
Are you planning on updating the dependencies at some point?

Some fixes made on the `ember-power-calendar` are needed by my application and atm im adding the most recent version of `ember-power-calendar` (0.12.0) manually to my package.json to fix some issues.

I have no clue if there are other side effects by updating only this package, but for me it seems to work alright, didn't run this addon separately with updated version, so maybe some tests are failing (which i doubt)

**Comment by cibernox** [comment]
AFAIK nothing is preventing this addon from update, it's just that I don't use it currently in any project. But by all means, if you have the chance to update the dependencies and the version of Ember I can merge it later today

**Comment by markusm7** [comment]
Perfect, going to make a PR

**Comment by markusm7** [comment]
Made a pull request https://github.com/cibernox/ember-power-datepicker/pull/36
