### ISSUE TITLE
Does not work with ember-basic-dropdown 2.x

### ISSUE THREAD

**Issue by ShenglinGuo** [cibernox/ember-power-datepicker#43]
the ember-power components are great thank you. We use both the ember-power-select and ember-power-datepicker, recently we upgrade to ember 3.11 and ember power select 3x, which has dependency on ember-basic-dropdown 2.x. But we found ember-power-datepicker does not work with ember-basic-dropdown 2.x. Is there any workaround to this issue, before the ember-power-datepicker is updated.

Thank you

**Comment by cibernox** [comment]
I'm aware of this, I'm working on an update in this branch: https://github.com/cibernox/ember-power-datepicker/pull/41

Hopefully I'll finish it this friday.

**Comment by cibernox** [comment]
This is now implemented. Give it a go!

**Comment by ShenglinGuo** [comment]
@cibernox Thanks for the quick response, the new 0.7.1 version is working well for us. Thank you again for the great components.
