### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jherdman** [cibernox/ember-power-datepicker#61]
Is it possible to have a release with the dependency updates?

**Comment by salaerts** [comment]
Yes! Can we get a new release with dependencies updates? At the moment I have to resolve ember-assign-helpers to 0.3.0 manually in the package.json file because of the mismatch in versions between different components.

`@project/shared
            ├─┬ @project/shared
            │ ├─┬ ember-power-datepicker
            │ │ └─┬ ember-power-calendar
            │ │   └── ember-assign-helper@0.2.0
            │ └─┬ ember-power-select
            │   └── ember-assign-helper@0.3.0
            ├─┬ ember-power-datepicker
            │ └─┬ ember-power-calendar
            │   └── ember-assign-helper@0.2.0
            └─┬ ember-power-select
              └── ember-assign-helper@0.3.0
`
