### ISSUE TITLE
Update ember v3.22.0...v3.28.5 & dependencies

### ISSUE THREAD

**Issue by mkszepp** [cibernox/ember-power-datepicker#70]
Update `ember-power-calendar` & `ember-power-calendar-moment` to the latest version after following releases:

- https://github.com/cibernox/ember-power-calendar-moment/issues/33
- https://github.com/cibernox/ember-power-calendar/pull/292

After this changes, there is possible to use this addon with Ember 4

**Comment by arei** [comment]
Still waiting on this please.

**Comment by mkszepp** [comment]
@cibernox can we get a release with this changes?

**Comment by gordon-addepar** [comment]
Would be nice to get clarity on the status of this addon – ie should we start using a fork or will it continue to be active etc?
